name: Build Back-End Service
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: chkout
        uses: actions/checkout@v2

      - name: Build Back-End
        run : |
          cd back-end
          docker build -t arunr039/back-end:${{github.run_number}} .
      - name: Login to Docker hub and push
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push arunr039/back-end:${{github.run_number}}

