name: Buld Frontend Service
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker image
        run: |
          cd front-end
          docker build -t arunr039/front-end:${{github.run_number}} .
      - name: Login to Docker hub and push
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push arunr039/front-end:${{github.run_number}}

      - name: Build Backend
        run: |
          cd ..
          cd back-end
          docker build -t arunr039/backend:${{github.run_number}}
      - name:  Push Image to Docker
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push arunr039/backend:${{github.run_number}}