# name: Build Backned Service
# on: workflow_dispatch

# jobs:
#   backend:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Build Backend
      
#         run: |
#           cd back-end
#           docker build -t arunr039/backend:${{github.run_number}}
#       - name:  Push Image to Docker
#         run: |
#           echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
#           docker push arunr039/backend:${{github.run_number}}