name: Infrastructure Creation
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: chkout
        uses: actions/checkout@v2

      - name: Build Front-End
        run : |
          cd back-end
          docker build -t arunr039/back-end:${{github.run_number}}
      - name: Login to Docker hub and push
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push arunr039/back-end:${{github.run_number}}

