name: Build Front-End Service
on: workflow_dispatchjobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: chkout
        uses: actions/checkout@v2

      - name: Build Front-End
        run : |
          cd frontend
          docker build -t arunr039/front-end:${{github.run_number}} .
      - name: Login to Docker hub and push
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push arunr039/front-end:${{github.run_number}}
