name: Build Frontend Service
on:
  workflow_dispatch
jobs:
  build:
    runs-on: self-hosted
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_DEFAULT_REGION: ap-south-1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform plan
        run: |
          cd infrastructure/modules/sns
          terraform plan