name: Infrastructure Creation
on: workflow_dispatch
env:
  PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
  HOSTNAME : ${{ secrets.SSH_KEY  }}
  USER_NAME : ${{ secrets.USER_NAME  }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: chkout
        uses: actions/checkout@v2
      - uses:  hashicorp/setup-terraform@v2
      - name: Initialize env
        run: |
          cd infrastructure/modules/sns
          bash aws.sh
          terraform init
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: plan
        run : |
          cd infrastructure/modules/sns
          terraform plan
      - name: login ec2
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@43.204.25.46 '   
      
